apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  containers:
  - name: consumer
    image: mycustomregistry.azurecr.io/golang-consumer:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: "/app"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
